# Site settings
author: Janet 
title: Software Engineering 
header-img: img/home-bg.png
email: kj688895@gmail.com
copyright_name: Janet 
description: > # this means to ignore newlines until "baseurl:"
  FT 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  j4netkim

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
